version: "3"
services:
    app:
        build: .
        ports:
            - "5000:80"
        volumes:
            - ./src:/var/www/html
        networks:
            global_networks:

networks:
    global_networks:
